package com.ik.service.miniprogram.service.impl;

import org.mybatis.extend.generic.service.impl.GenericServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ik.service.miniprogram.mapper.MpApiKeyMapper;
import com.ik.service.miniprogram.model.MpApiKey;
import com.ik.service.miniprogram.service.MpApiKeyService;

/**
 * ServiceImpl: MpApiKeyServiceImpl
 * Mapper : MpApiKeyMapper
 * Model  : MpApiKey
 *
 * This ServiceImpl generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
@Service
@Transactional
public class MpApiKeyServiceImpl extends GenericServiceImpl<MpApiKey, Integer, MpApiKeyMapper> implements MpApiKeyService {
    @Autowired
    private MpApiKeyMapper mpApiKeyMapper;

    @Override
    public MpApiKeyMapper getGenericMapper() {
        return mpApiKeyMapper;
    }
}