package com.ik.service.miniprogram.service.impl;

import org.mybatis.extend.generic.service.impl.GenericServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ik.service.miniprogram.mapper.TeacherStudentMapMapper;
import com.ik.service.miniprogram.model.TeacherStudentMap;
import com.ik.service.miniprogram.service.TeacherStudentMapService;

/**
 * ServiceImpl: TeacherStudentMapServiceImpl
 * Mapper : TeacherStudentMapMapper
 * Model  : TeacherStudentMap
 *
 * This ServiceImpl generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
@Service
@Transactional
public class TeacherStudentMapServiceImpl extends GenericServiceImpl<TeacherStudentMap, Integer, TeacherStudentMapMapper> implements TeacherStudentMapService {
    @Autowired
    private TeacherStudentMapMapper teacherStudentMapMapper;

    @Override
    public TeacherStudentMapMapper getGenericMapper() {
        return teacherStudentMapMapper;
    }
}