package com.ik.service.miniprogram.model;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.extend.generic.model.BaseModel;

/**
 * Model: EnrollInfo
 * Table: enroll_info
 * Alias: ei
 *
 * This Model generated by MyBatis Generator Extend.
 */
public class EnrollInfo extends BaseModel<Integer> implements Serializable {
    /**
     * 联系方式
     * phone
     */
    private String phone;

    /**
     * 
     * name
     */
    private String name;

    /**
     * 年级
     * grade
     */
    private Integer grade;

    /**
     * 邮箱
     * email
     */
    private String email;

    /**
     * 家庭地址
     * address
     */
    private String address;

    /**
     * 是否联系 0 ： 未联系；1：已联系
     * is_contacted
     */
    private Boolean isContacted;

    /**
     * 创建时间
     * created_at
     */
    private Date createdAt;

    /**
     * 更新时间
     * updated_at
     */
    private Date updatedAt;

    private static final long serialVersionUID = 1L;

    /**
     * 联系方式
     * phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 联系方式
     * phone
     *
     * @param phone 联系方式
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 
     * name
     */
    public String getName() {
        return name;
    }

    /**
     * 
     * name
     *
     * @param name 
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 年级
     * grade
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * 年级
     * grade
     *
     * @param grade 年级
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * 邮箱
     * email
     */
    public String getEmail() {
        return email;
    }

    /**
     * 邮箱
     * email
     *
     * @param email 邮箱
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 家庭地址
     * address
     */
    public String getAddress() {
        return address;
    }

    /**
     * 家庭地址
     * address
     *
     * @param address 家庭地址
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * 是否联系 0 ： 未联系；1：已联系
     * is_contacted
     */
    public Boolean getIsContacted() {
        return isContacted;
    }

    /**
     * 是否联系 0 ： 未联系；1：已联系
     * is_contacted
     *
     * @param isContacted 是否联系 0 ： 未联系；1：已联系
     */
    public void setIsContacted(Boolean isContacted) {
        this.isContacted = isContacted;
    }

    /**
     * 创建时间
     * created_at
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * 创建时间
     * created_at
     *
     * @param createdAt 创建时间
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 更新时间
     * updated_at
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * 更新时间
     * updated_at
     *
     * @param updatedAt 更新时间
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phone=").append(phone);
        sb.append(", name=").append(name);
        sb.append(", grade=").append(grade);
        sb.append(", email=").append(email);
        sb.append(", address=").append(address);
        sb.append(", isContacted=").append(isContacted);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EnrollInfo other = (EnrollInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}