package com.ik.service.miniprogram.model;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.extend.generic.model.BaseModel;

/**
 * Model: ExamPaper
 * Table: exam_papers
 * Alias: ep
 *
 * This Model generated by MyBatis Generator Extend.
 */
public class ExamPaper extends BaseModel<Integer> implements Serializable {
    /**
     * 试卷类型1：语文；2：数学；3：英语；4：物理；5：化学；6：生物；7：政治；8：历史；9：地理
     * paper_type
     */
    private Integer paperType;

    /**
     * 试卷名称
     * name
     */
    private String name;

    /**
     * 总分
     * total scores
     */
    private Integer totalScores;

    /**
     * 出卷人
     * set_person
     */
    private String setPerson;

    /**
     * 题目
     * question_ids
     */
    private String questionIds;

    /**
     * 创建时间
     * created_at
     */
    private Date createdAt;

    /**
     * 更新时间
     * updated_at
     */
    private Date updatedAt;

    private static final long serialVersionUID = 1L;

    /**
     * 试卷类型1：语文；2：数学；3：英语；4：物理；5：化学；6：生物；7：政治；8：历史；9：地理
     * paper_type
     */
    public Integer getPaperType() {
        return paperType;
    }

    /**
     * 试卷类型1：语文；2：数学；3：英语；4：物理；5：化学；6：生物；7：政治；8：历史；9：地理
     * paper_type
     *
     * @param paperType 试卷类型1：语文；2：数学；3：英语；4：物理；5：化学；6：生物；7：政治；8：历史；9：地理
     */
    public void setPaperType(Integer paperType) {
        this.paperType = paperType;
    }

    /**
     * 试卷名称
     * name
     */
    public String getName() {
        return name;
    }

    /**
     * 试卷名称
     * name
     *
     * @param name 试卷名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 总分
     * total scores
     */
    public Integer getTotalScores() {
        return totalScores;
    }

    /**
     * 总分
     * total scores
     *
     * @param totalScores 总分
     */
    public void setTotalScores(Integer totalScores) {
        this.totalScores = totalScores;
    }

    /**
     * 出卷人
     * set_person
     */
    public String getSetPerson() {
        return setPerson;
    }

    /**
     * 出卷人
     * set_person
     *
     * @param setPerson 出卷人
     */
    public void setSetPerson(String setPerson) {
        this.setPerson = setPerson;
    }

    /**
     * 题目
     * question_ids
     */
    public String getQuestionIds() {
        return questionIds;
    }

    /**
     * 题目
     * question_ids
     *
     * @param questionIds 题目
     */
    public void setQuestionIds(String questionIds) {
        this.questionIds = questionIds;
    }

    /**
     * 创建时间
     * created_at
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * 创建时间
     * created_at
     *
     * @param createdAt 创建时间
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 更新时间
     * updated_at
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * 更新时间
     * updated_at
     *
     * @param updatedAt 更新时间
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", paperType=").append(paperType);
        sb.append(", name=").append(name);
        sb.append(", totalScores=").append(totalScores);
        sb.append(", setPerson=").append(setPerson);
        sb.append(", questionIds=").append(questionIds);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ExamPaper other = (ExamPaper) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}