package com.ik.service.miniprogram.model;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.extend.generic.model.BaseModel;

/**
 * Model: Student
 * Table: students
 * Alias: st
 *
 * This Model generated by MyBatis Generator Extend.
 */
public class Student extends BaseModel<Integer> implements Serializable {
    /**
     * 年级
     * grade
     */
    private Integer grade;

    /**
     * 姓名
     * name
     */
    private String name;

    /**
     * 邮箱
     * email
     */
    private String email;

    /**
     * 微信openid
     * openid
     */
    private String openid;

    /**
     * 绑定手机
     * phone
     */
    private String phone;

    /**
     * 头像url
     * avatar_url
     */
    private String avatarUrl;

    /**
     * 性别 1：男；2：女
     * gender
     */
    private Integer gender;

    /**
     * 昵称
     * nick_name
     */
    private String nickName;

    /**
     * 是否设置个人信息
     * set_info
     */
    private Boolean setInfo;

    /**
     * 绑定老师的id
     * binded_teacherIds
     */
    private String bindedTeacherids;

    /**
     * 创建时间
     * created_at
     */
    private Date createdAt;

    /**
     * 更新时间
     * updated_at
     */
    private Date updatedAt;

    private static final long serialVersionUID = 1L;

    /**
     * 年级
     * grade
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * 年级
     * grade
     *
     * @param grade 年级
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * 姓名
     * name
     */
    public String getName() {
        return name;
    }

    /**
     * 姓名
     * name
     *
     * @param name 姓名
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 邮箱
     * email
     */
    public String getEmail() {
        return email;
    }

    /**
     * 邮箱
     * email
     *
     * @param email 邮箱
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 微信openid
     * openid
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * 微信openid
     * openid
     *
     * @param openid 微信openid
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * 绑定手机
     * phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 绑定手机
     * phone
     *
     * @param phone 绑定手机
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 头像url
     * avatar_url
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * 头像url
     * avatar_url
     *
     * @param avatarUrl 头像url
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * 性别 1：男；2：女
     * gender
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * 性别 1：男；2：女
     * gender
     *
     * @param gender 性别 1：男；2：女
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * 昵称
     * nick_name
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * 昵称
     * nick_name
     *
     * @param nickName 昵称
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * 是否设置个人信息
     * set_info
     */
    public Boolean getSetInfo() {
        return setInfo;
    }

    /**
     * 是否设置个人信息
     * set_info
     *
     * @param setInfo 是否设置个人信息
     */
    public void setSetInfo(Boolean setInfo) {
        this.setInfo = setInfo;
    }

    /**
     * 绑定老师的id
     * binded_teacherIds
     */
    public String getBindedTeacherids() {
        return bindedTeacherids;
    }

    /**
     * 绑定老师的id
     * binded_teacherIds
     *
     * @param bindedTeacherids 绑定老师的id
     */
    public void setBindedTeacherids(String bindedTeacherids) {
        this.bindedTeacherids = bindedTeacherids;
    }

    /**
     * 创建时间
     * created_at
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * 创建时间
     * created_at
     *
     * @param createdAt 创建时间
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 更新时间
     * updated_at
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * 更新时间
     * updated_at
     *
     * @param updatedAt 更新时间
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", grade=").append(grade);
        sb.append(", name=").append(name);
        sb.append(", email=").append(email);
        sb.append(", openid=").append(openid);
        sb.append(", phone=").append(phone);
        sb.append(", avatarUrl=").append(avatarUrl);
        sb.append(", gender=").append(gender);
        sb.append(", nickName=").append(nickName);
        sb.append(", setInfo=").append(setInfo);
        sb.append(", bindedTeacherids=").append(bindedTeacherids);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Student other = (Student) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}