package com.ik.service.miniprogram.model;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.extend.generic.model.BaseModel;

/**
 * Model: Teacher
 * Table: teachers
 * Alias: te
 *
 * This Model generated by MyBatis Generator Extend.
 */
public class Teacher extends BaseModel<Integer> implements Serializable {
    /**
     * 账户ID
     * account_id
     */
    private Integer accountId;

    /**
     * 老师类型1：语文；2：数学；3：英语；4：物理；5：化学；6：生物；7：政治；8：历史；9：地理
     * type
     */
    private Integer type;

    /**
     * 老师名称
     * name
     */
    private String name;

    /**
     * 手机号
     * phone
     */
    private String phone;

    /**
     * 
     * bindphone
     */
    private String bindphone;

    /**
     * 邮箱
     * email
     */
    private String email;

    /**
     * openid
     * openid
     */
    private String openid;

    /**
     * 创建时间
     * created_at
     */
    private Date createdAt;

    /**
     * 修改时间
     * updated_at
     */
    private Date updatedAt;

    private static final long serialVersionUID = 1L;

    /**
     * 账户ID
     * account_id
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * 账户ID
     * account_id
     *
     * @param accountId 账户ID
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * 老师类型1：语文；2：数学；3：英语；4：物理；5：化学；6：生物；7：政治；8：历史；9：地理
     * type
     */
    public Integer getType() {
        return type;
    }

    /**
     * 老师类型1：语文；2：数学；3：英语；4：物理；5：化学；6：生物；7：政治；8：历史；9：地理
     * type
     *
     * @param type 老师类型1：语文；2：数学；3：英语；4：物理；5：化学；6：生物；7：政治；8：历史；9：地理
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 老师名称
     * name
     */
    public String getName() {
        return name;
    }

    /**
     * 老师名称
     * name
     *
     * @param name 老师名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 手机号
     * phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 手机号
     * phone
     *
     * @param phone 手机号
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 
     * bindphone
     */
    public String getBindphone() {
        return bindphone;
    }

    /**
     * 
     * bindphone
     *
     * @param bindphone 
     */
    public void setBindphone(String bindphone) {
        this.bindphone = bindphone;
    }

    /**
     * 邮箱
     * email
     */
    public String getEmail() {
        return email;
    }

    /**
     * 邮箱
     * email
     *
     * @param email 邮箱
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * openid
     * openid
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * openid
     * openid
     *
     * @param openid openid
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * 创建时间
     * created_at
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * 创建时间
     * created_at
     *
     * @param createdAt 创建时间
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 修改时间
     * updated_at
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * 修改时间
     * updated_at
     *
     * @param updatedAt 修改时间
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accountId=").append(accountId);
        sb.append(", type=").append(type);
        sb.append(", name=").append(name);
        sb.append(", phone=").append(phone);
        sb.append(", bindphone=").append(bindphone);
        sb.append(", email=").append(email);
        sb.append(", openid=").append(openid);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Teacher other = (Teacher) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}