package com.bdxmx.miniprogram.service;

import com.bdxmx.miniprogram.model.AnswerSheet;
import org.mybatis.extend.generic.service.GenericService;

/**
 * Service: AnswerSheetService
 * Mapper : AnswerSheetMapper
 * Model  : AnswerSheet
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface AnswerSheetService extends GenericService<AnswerSheet, Integer> {
}