package com.bdxmx.miniprogram.service;

import org.mybatis.extend.generic.service.GenericService;

import com.alibaba.fastjson.JSONObject;
import com.bdxmx.miniprogram.model.ExamPaper;

/**
 * Service: ExamPaperService
 * Mapper : ExamPaperMapper
 * Model  : ExamPaper
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface ExamPaperService extends GenericService<ExamPaper, Integer> {
    ExamPaper saveExamPaper(Integer paperType, String name, Integer teacherId, String questionIds, Integer totalScore);

    ExamPaper updateExamPaper(Integer examPaperId, Integer paperType, String name, String questionIds,
            Integer totalScore);

    JSONObject getPaper(Integer examPaperId);
}