package com.bdxmx.miniprogram.service;

import com.bdxmx.miniprogram.model.MpApiKey;
import org.mybatis.extend.generic.service.GenericService;

/**
 * Service: MpApiKeyService
 * Mapper : MpApiKeyMapper
 * Model  : MpApiKey
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface MpApiKeyService extends GenericService<MpApiKey, Integer> {
}