package com.bdxmx.miniprogram.service;

import com.bdxmx.miniprogram.model.PcApiKey;
import org.mybatis.extend.generic.service.GenericService;

/**
 * Service: PcApiKeyService
 * Mapper : PcApiKeyMapper
 * Model  : PcApiKey
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface PcApiKeyService extends GenericService<PcApiKey, Integer> {
}