package com.bdxmx.miniprogram.service;

import com.bdxmx.miniprogram.model.Student;
import org.mybatis.extend.generic.service.GenericService;

/**
 * Service: StudentService
 * Mapper : StudentMapper
 * Model  : Student
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface StudentService extends GenericService<Student, Integer> {
}