package com.bdxmx.miniprogram.service;

import com.bdxmx.miniprogram.model.TeacherStudentMap;
import org.mybatis.extend.generic.service.GenericService;

/**
 * Service: TeacherStudentMapService
 * Mapper : TeacherStudentMapMapper
 * Model  : TeacherStudentMap
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface TeacherStudentMapService extends GenericService<TeacherStudentMap, Integer> {
}