package com.bdxmx.miniprogram.mapper;

import com.bdxmx.miniprogram.model.Account;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: AccountMapper
 * Model : Account
 * Table : accounts
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-04 13:49:32
 */
public interface AccountMapper extends GenericMapper<Account, Integer> {
}