package com.bdxmx.miniprogram.mapper;

import com.bdxmx.miniprogram.model.AnswerSheet;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: AnswerSheetMapper
 * Model : AnswerSheet
 * Table : answer_sheets
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface AnswerSheetMapper extends GenericMapper<AnswerSheet, Integer> {
}