package com.bdxmx.miniprogram.mapper;

import com.bdxmx.miniprogram.model.ExamPaper;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: ExamPaperMapper
 * Model : ExamPaper
 * Table : exam_papers
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface ExamPaperMapper extends GenericMapper<ExamPaper, Integer> {
}