package com.bdxmx.miniprogram.mapper;

import com.bdxmx.miniprogram.model.MpApiKey;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: MpApiKeyMapper
 * Model : MpApiKey
 * Table : mp_api_keys
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface MpApiKeyMapper extends GenericMapper<MpApiKey, Integer> {
}