package com.bdxmx.miniprogram.mapper;

import com.bdxmx.miniprogram.model.PcApiKey;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: PcApiKeyMapper
 * Model : PcApiKey
 * Table : pc_api_keys
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface PcApiKeyMapper extends GenericMapper<PcApiKey, Integer> {
}