package com.bdxmx.miniprogram.mapper;

import java.util.List;

import org.mybatis.extend.generic.mapper.GenericMapper;

import com.bdxmx.miniprogram.model.Question;

/**
 * Mapper: QuestionMapper
 * Model : Question
 * Table : questions
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface QuestionMapper extends GenericMapper<Question, Integer> {
    List<Question> getByIds(List<Integer> questionIds);
}