package com.bdxmx.miniprogram.mapper;

import com.bdxmx.miniprogram.model.Student;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: StudentMapper
 * Model : Student
 * Table : students
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface StudentMapper extends GenericMapper<Student, Integer> {
}