package com.bdxmx.miniprogram.mapper;

import com.bdxmx.miniprogram.model.TeacherStudentMap;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: TeacherStudentMapMapper
 * Model : TeacherStudentMap
 * Table : teacher_student_map
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface TeacherStudentMapMapper extends GenericMapper<TeacherStudentMap, Integer> {
}