package com.bdxmx.miniprogram.service.impl;

import com.bdxmx.miniprogram.mapper.AnswerSheetMapper;
import com.bdxmx.miniprogram.model.AnswerSheet;
import com.bdxmx.miniprogram.service.AnswerSheetService;
import org.mybatis.extend.generic.service.impl.GenericServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * ServiceImpl: AnswerSheetServiceImpl
 * Mapper : AnswerSheetMapper
 * Model  : AnswerSheet
 *
 * This ServiceImpl generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
@Service
@Transactional
public class AnswerSheetServiceImpl extends GenericServiceImpl<AnswerSheet, Integer, AnswerSheetMapper> implements AnswerSheetService {
    @Autowired
    private AnswerSheetMapper answerSheetMapper;

    @Override
    public AnswerSheetMapper getGenericMapper() {
        return answerSheetMapper;
    }
}