package com.bdxmx.miniprogram.service.impl;

import com.bdxmx.miniprogram.mapper.PcApiKeyMapper;
import com.bdxmx.miniprogram.model.PcApiKey;
import com.bdxmx.miniprogram.service.PcApiKeyService;
import org.mybatis.extend.generic.service.impl.GenericServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * ServiceImpl: PcApiKeyServiceImpl
 * Mapper : PcApiKeyMapper
 * Model  : PcApiKey
 *
 * This ServiceImpl generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
@Service
@Transactional
public class PcApiKeyServiceImpl extends GenericServiceImpl<PcApiKey, Integer, PcApiKeyMapper> implements PcApiKeyService {
    @Autowired
    private PcApiKeyMapper pcApiKeyMapper;

    @Override
    public PcApiKeyMapper getGenericMapper() {
        return pcApiKeyMapper;
    }
}