package com.ik.service.miniprogram.service;

import java.util.List;

import org.mybatis.extend.generic.service.GenericService;

import com.alibaba.fastjson.JSONObject;
import com.ik.service.miniprogram.model.Account;

/**
 * Service: AccountService
 * Mapper : AccountMapper
 * Model  : Account
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-04 13:49:32
 */
public interface AccountService extends GenericService<Account, Integer> {
    List<Account> getAccount(String phone);

    Account register(String phone, String password, String name, String email, String avatarUrl, Boolean gendar);

    JSONObject updateAccount(Integer accountId, String name, String email, String avatarUrl, Boolean gendar,
            Integer type);

    JSONObject updatePassword(Integer accountId, String password, String passwordNew);

    JSONObject loginVerify(String phone, String password);
}