package com.ik.service.miniprogram.service;

import org.mybatis.extend.generic.service.GenericService;

import com.ik.service.miniprogram.model.AnswerSheet;
import com.ik.service.miniprogram.vo.AnswerSheetRequest;

/**
 * Service: AnswerSheetService
 * Mapper : AnswerSheetMapper
 * Model  : AnswerSheet
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface AnswerSheetService extends GenericService<AnswerSheet, Integer> {
    void saveAnswerSheet(AnswerSheetRequest answerSheetRequest);

    void reviseAnswerSheet(AnswerSheetRequest answerSheetRequest);
}