package com.ik.service.miniprogram.service;

import org.mybatis.extend.generic.service.GenericService;

import com.alibaba.fastjson.JSONObject;
import com.ik.service.miniprogram.model.EnrollInfo;

/**
 * Service: EnrollInfoService
 * Mapper : EnrollInfoMapper
 * Model  : EnrollInfo
 *
 * This Service generated by MyBatis Generator Extend at 2019-04-13 10:21:18
 */
public interface EnrollInfoService extends GenericService<EnrollInfo, Integer> {
    JSONObject saveEnrollInfo(JSONObject params);
}