package com.ik.service.miniprogram.service;

import java.util.List;

import org.mybatis.extend.generic.service.GenericService;
import org.mybatis.extend.page.param.Page;

import com.alibaba.fastjson.JSONObject;
import com.ik.service.miniprogram.model.ExamPaper;
import com.ik.service.miniprogram.model.Teacher;

/**
 * Service: ExamPaperService
 * Mapper : ExamPaperMapper
 * Model  : ExamPaper
 *
 * This Service generated by MyBatis Generator Extend at 2018-12-04 10:26:51
 */
public interface ExamPaperService extends GenericService<ExamPaper, Integer> {
    ExamPaper saveExamPaper(Integer paperType, String name, Teacher teacher, String questionIds, Integer totalScore);

    ExamPaper updateExamPaper(Integer examPaperId, Integer paperType, String name, String questionIds,
            Integer totalScore);

    JSONObject getPaper(Integer examPaperId);

    List<ExamPaper> getPaperList(Integer teacherId,Page page);
}