package com.bdxmx.miniprogram.model;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.extend.generic.model.BaseModel;

/**
 * Model: Student
 * Table: students
 * Alias: st
 *
 * This Model generated by MyBatis Generator Extend.
 */
public class Student extends BaseModel<Integer> implements Serializable {
    /**
     * 用户类型0：普通用户；1：管理员
     * grade
     */
    private Integer grade;

    /**
     * 姓名
     * name
     */
    private String name;

    /**
     * 邮箱
     * email
     */
    private String email;

    /**
     * 微信openid
     * openid
     */
    private String openid;

    /**
     * 绑定手机
     * phone
     */
    private String phone;

    /**
     * 创建时间
     * created_at
     */
    private Date createdAt;

    /**
     * 更新时间
     * updated_at
     */
    private Date updatedAt;

    private static final long serialVersionUID = 1L;

    /**
     * 用户类型0：普通用户；1：管理员
     * grade
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * 用户类型0：普通用户；1：管理员
     * grade
     *
     * @param grade 用户类型0：普通用户；1：管理员
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * 姓名
     * name
     */
    public String getName() {
        return name;
    }

    /**
     * 姓名
     * name
     *
     * @param name 姓名
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 邮箱
     * email
     */
    public String getEmail() {
        return email;
    }

    /**
     * 邮箱
     * email
     *
     * @param email 邮箱
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 微信openid
     * openid
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * 微信openid
     * openid
     *
     * @param openid 微信openid
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * 绑定手机
     * phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 绑定手机
     * phone
     *
     * @param phone 绑定手机
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 创建时间
     * created_at
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * 创建时间
     * created_at
     *
     * @param createdAt 创建时间
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 更新时间
     * updated_at
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * 更新时间
     * updated_at
     *
     * @param updatedAt 更新时间
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", grade=").append(grade);
        sb.append(", name=").append(name);
        sb.append(", email=").append(email);
        sb.append(", openid=").append(openid);
        sb.append(", phone=").append(phone);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Student other = (Student) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}