package com.ik.service.miniprogram.mapper;

import com.ik.service.miniprogram.model.Account;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: AccountMapper
 * Model : Account
 * Table : accounts
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface AccountMapper extends GenericMapper<Account, Integer> {
}