package com.ik.service.miniprogram.mapper;

import com.ik.service.miniprogram.model.AnswerSheet;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: AnswerSheetMapper
 * Model : AnswerSheet
 * Table : answer_sheets
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface AnswerSheetMapper extends GenericMapper<AnswerSheet, Integer> {
}