package com.ik.service.miniprogram.mapper;

import com.ik.service.miniprogram.model.EnrollInfo;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: EnrollInfoMapper
 * Model : EnrollInfo
 * Table : enroll_info
 *
 * This Mapper generated by MyBatis Generator Extend at 2019-04-13 10:21:18
 */
public interface EnrollInfoMapper extends GenericMapper<EnrollInfo, Integer> {
}