package com.ik.service.miniprogram.mapper;

import com.ik.service.miniprogram.model.ExamPaper;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: ExamPaperMapper
 * Model : ExamPaper
 * Table : exam_papers
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface ExamPaperMapper extends GenericMapper<ExamPaper, Integer> {
}