package com.ik.service.miniprogram.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.extend.generic.mapper.GenericMapper;
import org.mybatis.extend.page.param.Page;

import com.ik.service.miniprogram.model.ExamPaper;

/**
 * Mapper: ExamPaperMapper
 * Model : ExamPaper
 * Table : exam_papers
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface ExamPaperMapper extends GenericMapper<ExamPaper, Integer> {
    List<ExamPaper> getPaperList(@Param("teacherId") Integer teacherId, @Param("page") Page page);
}