package com.ik.service.miniprogram.mapper;

import com.ik.service.miniprogram.model.MpApiKey;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: MpApiKeyMapper
 * Model : MpApiKey
 * Table : mp_api_keys
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface MpApiKeyMapper extends GenericMapper<MpApiKey, Integer> {
}