package com.ik.service.miniprogram.mapper;

import com.ik.service.miniprogram.model.PcApiKey;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: PcApiKeyMapper
 * Model : PcApiKey
 * Table : pc_api_keys
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface PcApiKeyMapper extends GenericMapper<PcApiKey, Integer> {
}