package com.ik.service.miniprogram.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.extend.generic.mapper.GenericMapper;
import org.mybatis.extend.page.param.Page;

import com.ik.service.miniprogram.model.Question;

/**
 * Mapper: QuestionMapper
 * Model : Question
 * Table : questions
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface QuestionMapper extends GenericMapper<Question, Integer> {
    List<Question> getByIds(@Param("questionIds") List<Integer> questionIds);

    List<Question> getByTeacherId(@Param("teacherId") Integer teacherId,@Param("page") Page page);
}