package com.ik.service.miniprogram.mapper;

import com.ik.service.miniprogram.model.Student;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: StudentMapper
 * Model : Student
 * Table : students
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface StudentMapper extends GenericMapper<Student, Integer> {
}