package com.ik.service.miniprogram.mapper;

import com.ik.service.miniprogram.model.Teacher;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: TeacherMapper
 * Model : Teacher
 * Table : teachers
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface TeacherMapper extends GenericMapper<Teacher, Integer> {
}