package com.ik.service.miniprogram.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.extend.generic.mapper.GenericMapper;
import org.mybatis.extend.page.param.Page;

import com.ik.service.miniprogram.model.Teacher;

/**
 * Mapper: TeacherMapper
 * Model : Teacher
 * Table : teachers
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface TeacherMapper extends GenericMapper<Teacher, Integer> {
    List<Teacher> getAllTeacherList(@Param("page") Page page, @Param("courseType") Integer courseType);
}