package com.ik.service.miniprogram.mapper;

import com.ik.service.miniprogram.model.TeacherStudentMap;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
 * Mapper: TeacherStudentMapMapper
 * Model : TeacherStudentMap
 * Table : teacher_student_map
 *
 * This Mapper generated by MyBatis Generator Extend at 2018-12-17 20:00:10
 */
public interface TeacherStudentMapMapper extends GenericMapper<TeacherStudentMap, Integer> {
}